"""facility title unique

Revision ID: fc7c92548e64
Revises: 72a0019992ca
Create Date: 2025-01-11 13:13:39.016868

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fc7c92548e64"
down_revision: Union[str, None] = "72a0019992ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "facilities", ["title"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "facilities", type_="unique")
    # ### end Alembic commands ###
